<?php

/**
 * Full ISO country list (name + iso2 + dial code), generated from the
 * `country-state-city` package so every country is selectable. Powers the
 * admin "Default country" picker (/admin/settings/general); reuse anywhere a
 * complete country dropdown is needed. Regenerate: node scratchpad/gen-countries.js
 */

return [
    ['code' => '+93', 'iso' => 'af', 'label' => 'Afghanistan (+93)'],
    ['code' => '+358', 'iso' => 'ax', 'label' => 'Aland Islands (+358)'],
    ['code' => '+355', 'iso' => 'al', 'label' => 'Albania (+355)'],
    ['code' => '+213', 'iso' => 'dz', 'label' => 'Algeria (+213)'],
    ['code' => '+1', 'iso' => 'as', 'label' => 'American Samoa (+1)'],
    ['code' => '+376', 'iso' => 'ad', 'label' => 'Andorra (+376)'],
    ['code' => '+244', 'iso' => 'ao', 'label' => 'Angola (+244)'],
    ['code' => '+1', 'iso' => 'ai', 'label' => 'Anguilla (+1)'],
    ['code' => '+672', 'iso' => 'aq', 'label' => 'Antarctica (+672)'],
    ['code' => '+1', 'iso' => 'ag', 'label' => 'Antigua And Barbuda (+1)'],
    ['code' => '+54', 'iso' => 'ar', 'label' => 'Argentina (+54)'],
    ['code' => '+374', 'iso' => 'am', 'label' => 'Armenia (+374)'],
    ['code' => '+297', 'iso' => 'aw', 'label' => 'Aruba (+297)'],
    ['code' => '+61', 'iso' => 'au', 'label' => 'Australia (+61)'],
    ['code' => '+43', 'iso' => 'at', 'label' => 'Austria (+43)'],
    ['code' => '+994', 'iso' => 'az', 'label' => 'Azerbaijan (+994)'],
    ['code' => '+973', 'iso' => 'bh', 'label' => 'Bahrain (+973)'],
    ['code' => '+880', 'iso' => 'bd', 'label' => 'Bangladesh (+880)'],
    ['code' => '+1', 'iso' => 'bb', 'label' => 'Barbados (+1)'],
    ['code' => '+375', 'iso' => 'by', 'label' => 'Belarus (+375)'],
    ['code' => '+32', 'iso' => 'be', 'label' => 'Belgium (+32)'],
    ['code' => '+501', 'iso' => 'bz', 'label' => 'Belize (+501)'],
    ['code' => '+229', 'iso' => 'bj', 'label' => 'Benin (+229)'],
    ['code' => '+1', 'iso' => 'bm', 'label' => 'Bermuda (+1)'],
    ['code' => '+975', 'iso' => 'bt', 'label' => 'Bhutan (+975)'],
    ['code' => '+591', 'iso' => 'bo', 'label' => 'Bolivia (+591)'],
    ['code' => '+599', 'iso' => 'bq', 'label' => 'Bonaire, Sint Eustatius and Saba (+599)'],
    ['code' => '+387', 'iso' => 'ba', 'label' => 'Bosnia and Herzegovina (+387)'],
    ['code' => '+267', 'iso' => 'bw', 'label' => 'Botswana (+267)'],
    ['code' => '+0055', 'iso' => 'bv', 'label' => 'Bouvet Island (+0055)'],
    ['code' => '+55', 'iso' => 'br', 'label' => 'Brazil (+55)'],
    ['code' => '+246', 'iso' => 'io', 'label' => 'British Indian Ocean Territory (+246)'],
    ['code' => '+673', 'iso' => 'bn', 'label' => 'Brunei (+673)'],
    ['code' => '+359', 'iso' => 'bg', 'label' => 'Bulgaria (+359)'],
    ['code' => '+226', 'iso' => 'bf', 'label' => 'Burkina Faso (+226)'],
    ['code' => '+257', 'iso' => 'bi', 'label' => 'Burundi (+257)'],
    ['code' => '+855', 'iso' => 'kh', 'label' => 'Cambodia (+855)'],
    ['code' => '+237', 'iso' => 'cm', 'label' => 'Cameroon (+237)'],
    ['code' => '+1', 'iso' => 'ca', 'label' => 'Canada (+1)'],
    ['code' => '+238', 'iso' => 'cv', 'label' => 'Cape Verde (+238)'],
    ['code' => '+1', 'iso' => 'ky', 'label' => 'Cayman Islands (+1)'],
    ['code' => '+236', 'iso' => 'cf', 'label' => 'Central African Republic (+236)'],
    ['code' => '+235', 'iso' => 'td', 'label' => 'Chad (+235)'],
    ['code' => '+56', 'iso' => 'cl', 'label' => 'Chile (+56)'],
    ['code' => '+86', 'iso' => 'cn', 'label' => 'China (+86)'],
    ['code' => '+61', 'iso' => 'cx', 'label' => 'Christmas Island (+61)'],
    ['code' => '+61', 'iso' => 'cc', 'label' => 'Cocos (Keeling) Islands (+61)'],
    ['code' => '+57', 'iso' => 'co', 'label' => 'Colombia (+57)'],
    ['code' => '+269', 'iso' => 'km', 'label' => 'Comoros (+269)'],
    ['code' => '+242', 'iso' => 'cg', 'label' => 'Congo (+242)'],
    ['code' => '+682', 'iso' => 'ck', 'label' => 'Cook Islands (+682)'],
    ['code' => '+506', 'iso' => 'cr', 'label' => 'Costa Rica (+506)'],
    ['code' => '+225', 'iso' => 'ci', 'label' => 'Cote D\'Ivoire (Ivory Coast) (+225)'],
    ['code' => '+385', 'iso' => 'hr', 'label' => 'Croatia (+385)'],
    ['code' => '+53', 'iso' => 'cu', 'label' => 'Cuba (+53)'],
    ['code' => '+599', 'iso' => 'cw', 'label' => 'Curaçao (+599)'],
    ['code' => '+357', 'iso' => 'cy', 'label' => 'Cyprus (+357)'],
    ['code' => '+420', 'iso' => 'cz', 'label' => 'Czech Republic (+420)'],
    ['code' => '+243', 'iso' => 'cd', 'label' => 'Democratic Republic of the Congo (+243)'],
    ['code' => '+45', 'iso' => 'dk', 'label' => 'Denmark (+45)'],
    ['code' => '+253', 'iso' => 'dj', 'label' => 'Djibouti (+253)'],
    ['code' => '+1', 'iso' => 'dm', 'label' => 'Dominica (+1)'],
    ['code' => '+1', 'iso' => 'do', 'label' => 'Dominican Republic (+1)'],
    ['code' => '+670', 'iso' => 'tl', 'label' => 'East Timor (+670)'],
    ['code' => '+593', 'iso' => 'ec', 'label' => 'Ecuador (+593)'],
    ['code' => '+20', 'iso' => 'eg', 'label' => 'Egypt (+20)'],
    ['code' => '+503', 'iso' => 'sv', 'label' => 'El Salvador (+503)'],
    ['code' => '+240', 'iso' => 'gq', 'label' => 'Equatorial Guinea (+240)'],
    ['code' => '+291', 'iso' => 'er', 'label' => 'Eritrea (+291)'],
    ['code' => '+372', 'iso' => 'ee', 'label' => 'Estonia (+372)'],
    ['code' => '+251', 'iso' => 'et', 'label' => 'Ethiopia (+251)'],
    ['code' => '+500', 'iso' => 'fk', 'label' => 'Falkland Islands (+500)'],
    ['code' => '+298', 'iso' => 'fo', 'label' => 'Faroe Islands (+298)'],
    ['code' => '+679', 'iso' => 'fj', 'label' => 'Fiji Islands (+679)'],
    ['code' => '+358', 'iso' => 'fi', 'label' => 'Finland (+358)'],
    ['code' => '+33', 'iso' => 'fr', 'label' => 'France (+33)'],
    ['code' => '+594', 'iso' => 'gf', 'label' => 'French Guiana (+594)'],
    ['code' => '+689', 'iso' => 'pf', 'label' => 'French Polynesia (+689)'],
    ['code' => '+262', 'iso' => 'tf', 'label' => 'French Southern Territories (+262)'],
    ['code' => '+241', 'iso' => 'ga', 'label' => 'Gabon (+241)'],
    ['code' => '+995', 'iso' => 'ge', 'label' => 'Georgia (+995)'],
    ['code' => '+49', 'iso' => 'de', 'label' => 'Germany (+49)'],
    ['code' => '+233', 'iso' => 'gh', 'label' => 'Ghana (+233)'],
    ['code' => '+350', 'iso' => 'gi', 'label' => 'Gibraltar (+350)'],
    ['code' => '+30', 'iso' => 'gr', 'label' => 'Greece (+30)'],
    ['code' => '+299', 'iso' => 'gl', 'label' => 'Greenland (+299)'],
    ['code' => '+1', 'iso' => 'gd', 'label' => 'Grenada (+1)'],
    ['code' => '+590', 'iso' => 'gp', 'label' => 'Guadeloupe (+590)'],
    ['code' => '+1', 'iso' => 'gu', 'label' => 'Guam (+1)'],
    ['code' => '+502', 'iso' => 'gt', 'label' => 'Guatemala (+502)'],
    ['code' => '+44', 'iso' => 'gg', 'label' => 'Guernsey and Alderney (+44)'],
    ['code' => '+224', 'iso' => 'gn', 'label' => 'Guinea (+224)'],
    ['code' => '+245', 'iso' => 'gw', 'label' => 'Guinea-Bissau (+245)'],
    ['code' => '+592', 'iso' => 'gy', 'label' => 'Guyana (+592)'],
    ['code' => '+509', 'iso' => 'ht', 'label' => 'Haiti (+509)'],
    ['code' => '+672', 'iso' => 'hm', 'label' => 'Heard Island and McDonald Islands (+672)'],
    ['code' => '+504', 'iso' => 'hn', 'label' => 'Honduras (+504)'],
    ['code' => '+852', 'iso' => 'hk', 'label' => 'Hong Kong S.A.R. (+852)'],
    ['code' => '+36', 'iso' => 'hu', 'label' => 'Hungary (+36)'],
    ['code' => '+354', 'iso' => 'is', 'label' => 'Iceland (+354)'],
    ['code' => '+91', 'iso' => 'in', 'label' => 'India (+91)'],
    ['code' => '+62', 'iso' => 'id', 'label' => 'Indonesia (+62)'],
    ['code' => '+98', 'iso' => 'ir', 'label' => 'Iran (+98)'],
    ['code' => '+964', 'iso' => 'iq', 'label' => 'Iraq (+964)'],
    ['code' => '+353', 'iso' => 'ie', 'label' => 'Ireland (+353)'],
    ['code' => '+972', 'iso' => 'il', 'label' => 'Israel (+972)'],
    ['code' => '+39', 'iso' => 'it', 'label' => 'Italy (+39)'],
    ['code' => '+1', 'iso' => 'jm', 'label' => 'Jamaica (+1)'],
    ['code' => '+81', 'iso' => 'jp', 'label' => 'Japan (+81)'],
    ['code' => '+44', 'iso' => 'je', 'label' => 'Jersey (+44)'],
    ['code' => '+962', 'iso' => 'jo', 'label' => 'Jordan (+962)'],
    ['code' => '+7', 'iso' => 'kz', 'label' => 'Kazakhstan (+7)'],
    ['code' => '+254', 'iso' => 'ke', 'label' => 'Kenya (+254)'],
    ['code' => '+686', 'iso' => 'ki', 'label' => 'Kiribati (+686)'],
    ['code' => '+383', 'iso' => 'xk', 'label' => 'Kosovo (+383)'],
    ['code' => '+965', 'iso' => 'kw', 'label' => 'Kuwait (+965)'],
    ['code' => '+996', 'iso' => 'kg', 'label' => 'Kyrgyzstan (+996)'],
    ['code' => '+856', 'iso' => 'la', 'label' => 'Laos (+856)'],
    ['code' => '+371', 'iso' => 'lv', 'label' => 'Latvia (+371)'],
    ['code' => '+961', 'iso' => 'lb', 'label' => 'Lebanon (+961)'],
    ['code' => '+266', 'iso' => 'ls', 'label' => 'Lesotho (+266)'],
    ['code' => '+231', 'iso' => 'lr', 'label' => 'Liberia (+231)'],
    ['code' => '+218', 'iso' => 'ly', 'label' => 'Libya (+218)'],
    ['code' => '+423', 'iso' => 'li', 'label' => 'Liechtenstein (+423)'],
    ['code' => '+370', 'iso' => 'lt', 'label' => 'Lithuania (+370)'],
    ['code' => '+352', 'iso' => 'lu', 'label' => 'Luxembourg (+352)'],
    ['code' => '+853', 'iso' => 'mo', 'label' => 'Macau S.A.R. (+853)'],
    ['code' => '+389', 'iso' => 'mk', 'label' => 'Macedonia (+389)'],
    ['code' => '+261', 'iso' => 'mg', 'label' => 'Madagascar (+261)'],
    ['code' => '+265', 'iso' => 'mw', 'label' => 'Malawi (+265)'],
    ['code' => '+60', 'iso' => 'my', 'label' => 'Malaysia (+60)'],
    ['code' => '+960', 'iso' => 'mv', 'label' => 'Maldives (+960)'],
    ['code' => '+223', 'iso' => 'ml', 'label' => 'Mali (+223)'],
    ['code' => '+356', 'iso' => 'mt', 'label' => 'Malta (+356)'],
    ['code' => '+44', 'iso' => 'im', 'label' => 'Man (Isle of) (+44)'],
    ['code' => '+692', 'iso' => 'mh', 'label' => 'Marshall Islands (+692)'],
    ['code' => '+596', 'iso' => 'mq', 'label' => 'Martinique (+596)'],
    ['code' => '+222', 'iso' => 'mr', 'label' => 'Mauritania (+222)'],
    ['code' => '+230', 'iso' => 'mu', 'label' => 'Mauritius (+230)'],
    ['code' => '+262', 'iso' => 'yt', 'label' => 'Mayotte (+262)'],
    ['code' => '+52', 'iso' => 'mx', 'label' => 'Mexico (+52)'],
    ['code' => '+691', 'iso' => 'fm', 'label' => 'Micronesia (+691)'],
    ['code' => '+373', 'iso' => 'md', 'label' => 'Moldova (+373)'],
    ['code' => '+377', 'iso' => 'mc', 'label' => 'Monaco (+377)'],
    ['code' => '+976', 'iso' => 'mn', 'label' => 'Mongolia (+976)'],
    ['code' => '+382', 'iso' => 'me', 'label' => 'Montenegro (+382)'],
    ['code' => '+1', 'iso' => 'ms', 'label' => 'Montserrat (+1)'],
    ['code' => '+212', 'iso' => 'ma', 'label' => 'Morocco (+212)'],
    ['code' => '+258', 'iso' => 'mz', 'label' => 'Mozambique (+258)'],
    ['code' => '+95', 'iso' => 'mm', 'label' => 'Myanmar (+95)'],
    ['code' => '+264', 'iso' => 'na', 'label' => 'Namibia (+264)'],
    ['code' => '+674', 'iso' => 'nr', 'label' => 'Nauru (+674)'],
    ['code' => '+977', 'iso' => 'np', 'label' => 'Nepal (+977)'],
    ['code' => '+31', 'iso' => 'nl', 'label' => 'Netherlands (+31)'],
    ['code' => '+687', 'iso' => 'nc', 'label' => 'New Caledonia (+687)'],
    ['code' => '+64', 'iso' => 'nz', 'label' => 'New Zealand (+64)'],
    ['code' => '+505', 'iso' => 'ni', 'label' => 'Nicaragua (+505)'],
    ['code' => '+227', 'iso' => 'ne', 'label' => 'Niger (+227)'],
    ['code' => '+234', 'iso' => 'ng', 'label' => 'Nigeria (+234)'],
    ['code' => '+683', 'iso' => 'nu', 'label' => 'Niue (+683)'],
    ['code' => '+672', 'iso' => 'nf', 'label' => 'Norfolk Island (+672)'],
    ['code' => '+850', 'iso' => 'kp', 'label' => 'North Korea (+850)'],
    ['code' => '+1', 'iso' => 'mp', 'label' => 'Northern Mariana Islands (+1)'],
    ['code' => '+47', 'iso' => 'no', 'label' => 'Norway (+47)'],
    ['code' => '+968', 'iso' => 'om', 'label' => 'Oman (+968)'],
    ['code' => '+92', 'iso' => 'pk', 'label' => 'Pakistan (+92)'],
    ['code' => '+680', 'iso' => 'pw', 'label' => 'Palau (+680)'],
    ['code' => '+970', 'iso' => 'ps', 'label' => 'Palestinian Territory Occupied (+970)'],
    ['code' => '+507', 'iso' => 'pa', 'label' => 'Panama (+507)'],
    ['code' => '+675', 'iso' => 'pg', 'label' => 'Papua new Guinea (+675)'],
    ['code' => '+595', 'iso' => 'py', 'label' => 'Paraguay (+595)'],
    ['code' => '+51', 'iso' => 'pe', 'label' => 'Peru (+51)'],
    ['code' => '+63', 'iso' => 'ph', 'label' => 'Philippines (+63)'],
    ['code' => '+870', 'iso' => 'pn', 'label' => 'Pitcairn Island (+870)'],
    ['code' => '+48', 'iso' => 'pl', 'label' => 'Poland (+48)'],
    ['code' => '+351', 'iso' => 'pt', 'label' => 'Portugal (+351)'],
    ['code' => '+1', 'iso' => 'pr', 'label' => 'Puerto Rico (+1)'],
    ['code' => '+974', 'iso' => 'qa', 'label' => 'Qatar (+974)'],
    ['code' => '+262', 'iso' => 're', 'label' => 'Reunion (+262)'],
    ['code' => '+40', 'iso' => 'ro', 'label' => 'Romania (+40)'],
    ['code' => '+7', 'iso' => 'ru', 'label' => 'Russia (+7)'],
    ['code' => '+250', 'iso' => 'rw', 'label' => 'Rwanda (+250)'],
    ['code' => '+290', 'iso' => 'sh', 'label' => 'Saint Helena (+290)'],
    ['code' => '+1', 'iso' => 'kn', 'label' => 'Saint Kitts And Nevis (+1)'],
    ['code' => '+1', 'iso' => 'lc', 'label' => 'Saint Lucia (+1)'],
    ['code' => '+508', 'iso' => 'pm', 'label' => 'Saint Pierre and Miquelon (+508)'],
    ['code' => '+1', 'iso' => 'vc', 'label' => 'Saint Vincent And The Grenadines (+1)'],
    ['code' => '+590', 'iso' => 'bl', 'label' => 'Saint-Barthelemy (+590)'],
    ['code' => '+590', 'iso' => 'mf', 'label' => 'Saint-Martin (French part) (+590)'],
    ['code' => '+685', 'iso' => 'ws', 'label' => 'Samoa (+685)'],
    ['code' => '+378', 'iso' => 'sm', 'label' => 'San Marino (+378)'],
    ['code' => '+239', 'iso' => 'st', 'label' => 'Sao Tome and Principe (+239)'],
    ['code' => '+966', 'iso' => 'sa', 'label' => 'Saudi Arabia (+966)'],
    ['code' => '+221', 'iso' => 'sn', 'label' => 'Senegal (+221)'],
    ['code' => '+381', 'iso' => 'rs', 'label' => 'Serbia (+381)'],
    ['code' => '+248', 'iso' => 'sc', 'label' => 'Seychelles (+248)'],
    ['code' => '+232', 'iso' => 'sl', 'label' => 'Sierra Leone (+232)'],
    ['code' => '+65', 'iso' => 'sg', 'label' => 'Singapore (+65)'],
    ['code' => '+1721', 'iso' => 'sx', 'label' => 'Sint Maarten (Dutch part) (+1721)'],
    ['code' => '+421', 'iso' => 'sk', 'label' => 'Slovakia (+421)'],
    ['code' => '+386', 'iso' => 'si', 'label' => 'Slovenia (+386)'],
    ['code' => '+677', 'iso' => 'sb', 'label' => 'Solomon Islands (+677)'],
    ['code' => '+252', 'iso' => 'so', 'label' => 'Somalia (+252)'],
    ['code' => '+27', 'iso' => 'za', 'label' => 'South Africa (+27)'],
    ['code' => '+500', 'iso' => 'gs', 'label' => 'South Georgia (+500)'],
    ['code' => '+82', 'iso' => 'kr', 'label' => 'South Korea (+82)'],
    ['code' => '+211', 'iso' => 'ss', 'label' => 'South Sudan (+211)'],
    ['code' => '+34', 'iso' => 'es', 'label' => 'Spain (+34)'],
    ['code' => '+94', 'iso' => 'lk', 'label' => 'Sri Lanka (+94)'],
    ['code' => '+249', 'iso' => 'sd', 'label' => 'Sudan (+249)'],
    ['code' => '+597', 'iso' => 'sr', 'label' => 'Suriname (+597)'],
    ['code' => '+47', 'iso' => 'sj', 'label' => 'Svalbard And Jan Mayen Islands (+47)'],
    ['code' => '+268', 'iso' => 'sz', 'label' => 'Swaziland (+268)'],
    ['code' => '+46', 'iso' => 'se', 'label' => 'Sweden (+46)'],
    ['code' => '+41', 'iso' => 'ch', 'label' => 'Switzerland (+41)'],
    ['code' => '+963', 'iso' => 'sy', 'label' => 'Syria (+963)'],
    ['code' => '+886', 'iso' => 'tw', 'label' => 'Taiwan (+886)'],
    ['code' => '+992', 'iso' => 'tj', 'label' => 'Tajikistan (+992)'],
    ['code' => '+255', 'iso' => 'tz', 'label' => 'Tanzania (+255)'],
    ['code' => '+66', 'iso' => 'th', 'label' => 'Thailand (+66)'],
    ['code' => '+1', 'iso' => 'bs', 'label' => 'The Bahamas (+1)'],
    ['code' => '+220', 'iso' => 'gm', 'label' => 'The Gambia (+220)'],
    ['code' => '+228', 'iso' => 'tg', 'label' => 'Togo (+228)'],
    ['code' => '+690', 'iso' => 'tk', 'label' => 'Tokelau (+690)'],
    ['code' => '+676', 'iso' => 'to', 'label' => 'Tonga (+676)'],
    ['code' => '+1', 'iso' => 'tt', 'label' => 'Trinidad And Tobago (+1)'],
    ['code' => '+216', 'iso' => 'tn', 'label' => 'Tunisia (+216)'],
    ['code' => '+90', 'iso' => 'tr', 'label' => 'Turkey (+90)'],
    ['code' => '+993', 'iso' => 'tm', 'label' => 'Turkmenistan (+993)'],
    ['code' => '+1', 'iso' => 'tc', 'label' => 'Turks And Caicos Islands (+1)'],
    ['code' => '+688', 'iso' => 'tv', 'label' => 'Tuvalu (+688)'],
    ['code' => '+256', 'iso' => 'ug', 'label' => 'Uganda (+256)'],
    ['code' => '+380', 'iso' => 'ua', 'label' => 'Ukraine (+380)'],
    ['code' => '+971', 'iso' => 'ae', 'label' => 'United Arab Emirates (+971)'],
    ['code' => '+44', 'iso' => 'gb', 'label' => 'United Kingdom (+44)'],
    ['code' => '+1', 'iso' => 'us', 'label' => 'United States (+1)'],
    ['code' => '+1', 'iso' => 'um', 'label' => 'United States Minor Outlying Islands (+1)'],
    ['code' => '+598', 'iso' => 'uy', 'label' => 'Uruguay (+598)'],
    ['code' => '+998', 'iso' => 'uz', 'label' => 'Uzbekistan (+998)'],
    ['code' => '+678', 'iso' => 'vu', 'label' => 'Vanuatu (+678)'],
    ['code' => '+379', 'iso' => 'va', 'label' => 'Vatican City State (Holy See) (+379)'],
    ['code' => '+58', 'iso' => 've', 'label' => 'Venezuela (+58)'],
    ['code' => '+84', 'iso' => 'vn', 'label' => 'Vietnam (+84)'],
    ['code' => '+1', 'iso' => 'vg', 'label' => 'Virgin Islands (British) (+1)'],
    ['code' => '+1', 'iso' => 'vi', 'label' => 'Virgin Islands (US) (+1)'],
    ['code' => '+681', 'iso' => 'wf', 'label' => 'Wallis And Futuna Islands (+681)'],
    ['code' => '+212', 'iso' => 'eh', 'label' => 'Western Sahara (+212)'],
    ['code' => '+967', 'iso' => 'ye', 'label' => 'Yemen (+967)'],
    ['code' => '+260', 'iso' => 'zm', 'label' => 'Zambia (+260)'],
    ['code' => '+263', 'iso' => 'zw', 'label' => 'Zimbabwe (+263)'],
];
